<a href="https://colab.research.google.com/github/MUHAMMAD-SULEMAN-10/NumPy/blob/main/numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
l = [1,2,3,4]


In [ ]:
arr = np.array(l)

In [ ]:
arr

In [ ]:
type(arr)

In [ ]:
#deimensions
#2D

array = np.array([[1,2], [3,4]])

In [ ]:
array.shape


In [ ]:
array.size

In [ ]:
array.ndim

In [ ]:
arr_3d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])


In [ ]:

print(arr_3d)
print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)

In [ ]:

print(arr_3d)
print("Dimensions:", arr_3d.ndim)
print("Shape:", arr_3d.shape)

In [ ]:
np.asarray(l)

#asarray is a function

In [ ]:
a = [2,3,4]

In [ ]:
#asanarray we can also used funciton

np.asanyarray(a)


In [ ]:
#use matrix

b = np.matrix(l)

#matrx by default is a 2D
#matrix is a subset of array

In [ ]:
b

In [ ]:
# now if we used np on the b asanyarray it will  remain the matrix


np.asanyarray(b)

In [ ]:
a = np.array(l)

In [ ]:
a

In [ ]:
#create a new variable c and assign a


c = a



In [ ]:
c

In [ ]:
a

In [ ]:
#if we chnaged the in c update the values then change the list
#and c will poin the same variable in the memory location and if we change in the c then will also occure in the a.

#it is a shallow copy

c[0] = 100

In [ ]:
c

In [ ]:
#now the changed will also be in the a 100 added in the a list also

a

In [ ]:
d = np.copy(a)

In [ ]:
d

In [ ]:
a

In [ ]:
#now change in the a

a[1] = 400

In [ ]:
a

In [ ]:
# But if we check the d value then there will be no change in the d

d

#because we compeletely copy it in a new location. d has new data location not the a location.

# its a deep copy concept.


In [ ]:
# Generate different different diemensions of array

np.fromfunction(lambda i,j : i==j, (3,3))

#Here we are creating the 3*3 = 9 elements matrix and like 0,1,2 row and then 0,1,2 col

In [ ]:
np.fromfunction(lambda i,j : i*j, (3,3))

# fromfunction is type of a function which will help us to in terms of arrays at any point of time.

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable ,float)

# fromiter function we can also make an array



In [ ]:
# fromstring function if we passed it will convert the dtring into an array

np.fromstring('234 234 555', sep=' ') # separate on the basis of the space

In [ ]:

np.fromstring('234,44', sep=',')

# Datatypes in Numpy

In [ ]:
# make a list

l = [1,2,3,4,5]


In [ ]:
arr = np.array(l)

In [ ]:
arr

In [ ]:
# if we want to check the dimensions of the array

In [ ]:
arr.ndim

In [ ]:
arr2 = np.array([[1,2,3,4], [2,3,4,5]])

In [ ]:
arr2

In [ ]:
arr2.ndim

In [ ]:
# Now i want check the size of the arr2

arr2.size

#will give the elements of the arr2

In [ ]:
arr.shape

# shape will tell about the rows and cols

In [ ]:
arr2.shape

In [ ]:
#want to check the data type

arr.dtype

In [ ]:
arr2.dtype

In [ ]:
# make another an array

ar22 = np.array([(1.4,45,45), (23,45,66)])


In [ ]:
ar22

In [ ]:
ar22.dtype

#it will be float

##TensorFlow Fundamentals - Scalars, Vectors, Matrices, and Tensors


In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

### Scalar/Constant

In [ ]:
# Create a scalar
scalar = tf.constant(24)
scalar

In [ ]:
# Check the number of dimensions (rank) of the scalar
scalar.ndim  # Also the Rank of the scalar

##Vector

In [ ]:

# Create a vector
vector = tf.constant([12, 24])
vector

In [ ]:
# Check the number of dimensions (rank) of the vector
vector.ndim  # Rank


## Matrix


In [ ]:
matrix = tf.constant([[12, 24],
                      [36, 48]])
matrix

In [ ]:
matrix.ndim  # Rank

In [ ]:
# Create another matrix with 3 rows and 2 columns
one_more_matrix = tf.constant([[1,2,3],
                               [4,5,6]])
one_more_matrix

In [ ]:
# Check the number of dimensions
one_more_matrix.ndim

## # Tensor

In [ ]:
# Create a tensor (3D or higher dimensional array)
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],

                      [[4,5,6],
                       [7,8,9]],

                      [[7,8,9],
                       [10,11,12]]])
tensor


In [ ]:
# Check the number of dimensions (rank) of the tensor
tensor.ndim

In [ ]:
print("\n" + "="*50)
print("SUMMARY")
print("="*50)
print(f"Scalar: {scalar.numpy()}, ndim: {scalar.ndim}, shape: {scalar.shape}")
print(f"Vector: {vector.numpy()}, ndim: {vector.ndim}, shape: {vector.shape}")
print(f"Matrix: \n{matrix.numpy()}, \nndim: {matrix.ndim}, shape: {matrix.shape}")
print(f"Tensor shape: {tensor.shape}, ndim: {tensor.ndim}")
print("="*50)

##range function

In [ ]:
# range function
range (5)

In [ ]:
#call in a list

list(range(5))

In [ ]:
# now can we generate the floating poin number in a range

#not possible

list(range(0.1 , 4))

##arange function

In [ ]:
#but the default in the numpy arange will work and generate the numbers in a float

np.arange(2.3, 5.6)

In [ ]:

np.arange(2.3, 5.6, .3) # .3 here is a jump

In [ ]:
list(np.arange(2.3, 5.6))


#numpy here tells us we can not only generate the interger values we can also generate the points vlaues.

## linspace function

In [ ]:
# linspace function

#it will take a line 1 to 5 and will divide and produce in 10 data set
np.linspace(1,5, 10)

##  zeors function

In [ ]:
# zeors function

# it will create the one D array take data 5

np.zeros(5) # 5 means here 1D will

In [ ]:
np.zeros((3,4)) # will be 3 rows and 5 cols in a 2D format

In [ ]:
np.zeros((3,4,2)) # this is a 3D and 3 here is kind of 3 cross mattrics and 4*2 = 8 elements

In [ ]:
np.zeros((3,4,2,3)) # here 3 is indiecate we have 3 matircs and each is 4D and 4 indicates we have 4 and 2 * 3 = 6 elems each have

## ones funciton

In [ ]:
# ones funciton


np.ones(4)

In [ ]:
np.ones((2,3))  #2D , 2 rows , 3 cols

In [ ]:
on = np.ones((3,4,4)) #3D , 4 rows , 4 cols

In [ ]:
on

In [ ]:
on.ndim

In [ ]:
on *4 #now it will add 4 to each matric

## empty function

In [ ]:
# empty function

#now the empty array has been created

np.empty((3,6))

In [ ]:
# entity matric create with the eye and dimensions is same and in the diognal have 1,1,1...
np.eye(4)

## linspace funciton

In [ ]:
# linspace funciton

np.linspace(2,4, 20)

## logspace funcition

In [ ]:
# logspace funcition

#same it will also create a log data of in 10 datapoints from 2 to 5

np.logspace(2,5, 10)

In [ ]:
#but we want to calculate on the base 2

np.logspace(2,5, 10, base=2)

# some important functions in the numpy

In [ ]:
# random function
# will produce random data

np.random.randn(3,4) # 3 cross 4 have 3 rows and 4 cols

In [ ]:
arr = np.random.randn(3,4)

#randn will geenrate the data where the mean is 0 and std = 1

In [ ]:
arr

In [ ]:
# but now we want to store this random data in a data frame for it we need to import the pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

In [ ]:
np.random.rand(3,4)

# here the rand will just randomly produce the data not beteen in 1 and 0

##randint fucniton

In [ ]:
# randint fucniton
# will generate the interger data set only


data=np.random.randint(1,110, (300,400)) # 300 rows , 400 are cols

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
#now store this data in a csv file


(df).to_csv('test.csv')

## reshape function

In [ ]:
arr1 = np.random.rand(3,4)

In [ ]:
arr1

In [ ]:
# reshape function

#it will widley used in ML during the data analysis

arr1 = np.random.rand(6,2)

In [ ]:
arr1

In [ ]:
arr1.reshape((6,-1)) # it will convert in a 6,2 automatically and assume the - 1 ==2

In [ ]:
arr.reshape(6,3)

##get a specific value

In [ ]:
# get a specific value
arr1[1][1]


In [ ]:
arr1[0:5]

In [ ]:
arr1[1:2]

In [ ]:
arr1[2:5,1] # start from 2 row and include 5th col and in this rows and cols get the values in a colom 1 with respect to dimension

In [ ]:
#make a random data

arr = np.random.randint(1,100, (5,5))

In [ ]:
arr

In [ ]:
#now get the data grater than 50

arr>50

In [ ]:
#now get the true data only


# make a array and then get its a subsetting.
arr[arr>50]

In [ ]:
# arr is availabel


arr

In [ ]:
#now i want a specific data from the array

# these values: 76,22  51,86

arr[2:4, [1,2]] # 2 and 4 are rows but till 3 work and 1, 2 are cols

In [ ]:
# want to get 15 value

arr[0][0]

In [ ]:
# add a new value at 1st
# data manuplation


arr[0][0] = 5000

In [ ]:
arr

In [ ]:
# inbuilt funcitons genrate the random data in arrays

arr1 = np.random.randint(1,3 , (3,3))

arr2 = np.random.randint(1,3 , (3,3))

In [ ]:
arr1

In [ ]:
arr2

##Mathamathical functions

In [ ]:
# nwo add these two arrays data
# it will adds the numbers on the basis of the indexes mapping will occure

arr1+arr2

In [ ]:
arr1-arr2

In [ ]:
arr1/arr2

In [ ]:
arr1*arr2
# it will be index wisse multiplication not the matriics multiplication

In [ ]:
# now how we can do matrices multiplication

# in which the 1st rows mul with the first col1,col2,col3 and so on.......

# and also the col values in the first matrix equal with the 2nd matrix col

In [ ]:
# use @ fro the matrix multiplication in numpy


arr1@arr2

In [ ]:
arr1/0

#it will give us infinity

In [ ]:
arr1 +100

In [ ]:
arr1**2 # add the power one by one

In [ ]:
# Broadcasting in Numpy

arr4 = np.zeros((4,4))

In [ ]:
arr4

In [ ]:
row = np.array([1,2,3,4])

In [ ]:
row

In [ ]:
arr4 + row

# it will add row wise values and we are changing the values in a row
# this a row wise broadcasting adding one by one.

In [ ]:
row.ndim

In [ ]:
row.shape

In [ ]:
row.T #take a transpose but it will not traspose due to 1 row



In [ ]:
col = np.array([[1,2,3,4]])

In [ ]:
col.T # its changed due to 2D

In [ ]:
col # it will same

In [ ]:
col.T + arr4


# here we are doing the col broadcasting one by one

#Matrix Library

##matlib = Matrix Library

In [ ]:
import numpy.matlib as nm

In [ ]:

np.zeros(5) # it will create matrix

#not the array it will careate

In [ ]:

np.ones((3,4))

In [ ]:

np.eye(5)

In [ ]:
#More maths opearation


array2 = np.random.randint(1,4 , (3,4))

In [ ]:
np.mean(array2)

In [ ]:
np.median(array2)

In [ ]:
np.std(array2)

In [ ]:
np.var(array2)

In [ ]:
array2

In [ ]:
# take a sqr root

np.sqrt(array2)

In [ ]:
# take a exponantional

np.exp(array2)

In [ ]:
# take a Log10


np.log10(array2)

##Linear Algebra

In [ ]:
arr1 = np.random.randint([[2,3], [4,5]])

In [ ]:
arr1

array([[1, 2],
       [1, 4]])

In [ ]:

arr2 = np.random.randint([[5,3], [2,5]])

In [ ]:
arr2

array([[3, 0],
       [1, 2]])

In [ ]:
np.dot(arr1, arr2)

array([[5, 4],
       [7, 8]])

In [ ]:
arr1@arr2

array([[5, 4],
       [7, 8]])