<a href="https://colab.research.google.com/github/MUHAMMAD-SULEMAN-10/NumPy-/blob/main/Numpy_part_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Array Mnupulation



In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10 , (3,4))

In [ ]:
arr

array([[8, 7, 5, 6],
       [7, 2, 6, 1],
       [1, 1, 5, 3]])

In [ ]:
# Now i want to manipulate this data

arr.reshape(6,2)

array([[8, 7],
       [5, 6],
       [7, 2],
       [6, 1],
       [1, 1],
       [5, 3]])

In [ ]:
arr.reshape(2,6)

array([[8, 7, 5, 6, 7, 2],
       [6, 1, 1, 1, 5, 3]])

In [ ]:
arr.reshape(2,7)

# becausei have only 12 values

ValueError: cannot reshape array of size 12 into shape (2,7)

In [ ]:
arr.T

array([[8, 7, 1],
       [7, 2, 1],
       [5, 6, 5],
       [6, 1, 3]])

In [ ]:
arr

array([[8, 7, 5, 6],
       [7, 2, 6, 1],
       [1, 1, 5, 3]])

In [ ]:
# Flatten function

#it will convert into a single row into 1D

arr.flatten()

array([8, 7, 5, 6, 7, 2, 6, 1, 1, 1, 5, 3])

In [ ]:
arr1 = np.array([1,2,3,3,4])

In [ ]:
arr1.ndim

1

In [ ]:
np.expand_dims(arr1, axis = 1)  #axis = 1 across colom

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [ ]:
np.expand_dims(arr1, axis = 0) #axis = 1 across row

array([[1, 2, 3, 3, 4]])

In [ ]:
arr

array([[8, 7, 5, 6],
       [7, 2, 6, 1],
       [1, 1, 5, 3]])

In [ ]:
np.squeeze(arr)

#not working on this data

array([[8, 7, 5, 6],
       [7, 2, 6, 1],
       [1, 1, 5, 3]])

In [ ]:
data = np.array([[1], [2], [3]])


In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data)

#now it hase converted into a one array if in the previous array has 1 ,  1 elements

array([1, 2, 3])

In [ ]:
#repeat function in a numpy

np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [ ]:
# roll funciton

#means it roll the data ghuma raha ha shift kr raha ha
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [ ]:
arr1

array([1, 2, 3, 3, 4])

In [ ]:
# diagonal function

np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

## Binary Opearions in Numpy

In [ ]:
arr1 = np.random.randint(1,10, (3,4))

In [ ]:
arr1

array([[4, 5, 2, 1],
       [2, 7, 1, 1],
       [6, 9, 4, 4]])

In [ ]:
arr2 = np.random.randint(1,10, (3,4))

In [ ]:
arr2

array([[4, 3, 9, 1],
       [3, 3, 3, 8],
       [3, 6, 9, 1]])

In [ ]:
arr1 + arr2

array([[ 8,  8, 11,  2],
       [ 5, 10,  4,  9],
       [ 9, 15, 13,  5]])

In [ ]:
arr1 * arr2

array([[16, 15, 18,  1],
       [ 6, 21,  3,  8],
       [18, 54, 36,  4]])

In [ ]:
arr1 - arr2

array([[ 0,  2, -7,  0],
       [-1,  4, -2, -7],
       [ 3,  3, -5,  3]])

In [ ]:
arr1 / arr2

array([[1.        , 1.66666667, 0.22222222, 1.        ],
       [0.66666667, 2.33333333, 0.33333333, 0.125     ],
       [2.        , 1.5       , 0.44444444, 4.        ]])

In [ ]:
arr1 % arr2

array([[0, 2, 2, 0],
       [2, 1, 1, 1],
       [0, 3, 4, 0]])

In [ ]:
arr ** arr2

array([[   4096,     343, 1953125,       6],
       [    343,       8,     216,       1],
       [      1,       1, 1953125,       3]])

## Arthematic OPerations

In [ ]:
arr1 & arr2

array([[4, 1, 0, 1],
       [2, 3, 1, 0],
       [2, 0, 0, 0]])

In [ ]:
~arr1 # Negation

array([[ -5,  -6,  -3,  -2],
       [ -3,  -8,  -2,  -2],
       [ -7, -10,  -5,  -5]])

In [ ]:
arr1|arr2 # OR opearations

array([[ 4,  7, 11,  1],
       [ 3,  7,  3,  9],
       [ 7, 15, 13,  5]])

In [ ]:
arr1 > arr2

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True,  True, False,  True]])

# String functions

In [ ]:
arr = np.array(['suleman', 'Afzal'])

In [ ]:
arr

array(['suleman', 'Afzal'], dtype='<U7')

In [ ]:
np.char.upper(arr)

#what is char here it is a class inside it has funcitons

array(['SULEMAN', 'AFZAL'], dtype='<U7')

In [ ]:
#covert into title case

np.char.title(arr)

array(['Suleman', 'Afzal'], dtype='<U7')

In [ ]:
np.char.capitalize(arr)

array(['Suleman', 'Afzal'], dtype='<U7')

# Mathamathical functions


In [ ]:
# sin , cosine , tan

arr1

array([[4, 5, 2, 1],
       [2, 7, 1, 1],
       [6, 9, 4, 4]])

In [ ]:
np.sin(arr1)

array([[-0.7568025 , -0.95892427,  0.90929743,  0.84147098],
       [ 0.90929743,  0.6569866 ,  0.84147098,  0.84147098],
       [-0.2794155 ,  0.41211849, -0.7568025 , -0.7568025 ]])

In [ ]:
np.cos(arr1)

array([[-0.65364362,  0.28366219, -0.41614684,  0.54030231],
       [-0.41614684,  0.75390225,  0.54030231,  0.54030231],
       [ 0.96017029, -0.91113026, -0.65364362, -0.65364362]])

In [ ]:
np.tan(arr1)

array([[ 1.15782128, -3.38051501, -2.18503986,  1.55740772],
       [-2.18503986,  0.87144798,  1.55740772,  1.55740772],
       [-0.29100619, -0.45231566,  1.15782128,  1.15782128]])

In [ ]:
np.tanh(arr1)

array([[0.9993293 , 0.9999092 , 0.96402758, 0.76159416],
       [0.96402758, 0.99999834, 0.76159416, 0.76159416],
       [0.99998771, 0.99999997, 0.9993293 , 0.9993293 ]])

In [ ]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.30103   , 0.        ],
       [0.30103   , 0.84509804, 0.        , 0.        ],
       [0.77815125, 0.95424251, 0.60205999, 0.60205999]])

In [ ]:
np.exp(arr1)

array([[5.45981500e+01, 1.48413159e+02, 7.38905610e+00, 2.71828183e+00],
       [7.38905610e+00, 1.09663316e+03, 2.71828183e+00, 2.71828183e+00],
       [4.03428793e+02, 8.10308393e+03, 5.45981500e+01, 5.45981500e+01]])

In [ ]:
np.sqrt(arr1)

array([[2.        , 2.23606798, 1.41421356, 1.        ],
       [1.41421356, 2.64575131, 1.        , 1.        ],
       [2.44948974, 3.        , 2.        , 2.        ]])

In [ ]:
np.power(arr1, 2)

array([[16, 25,  4,  1],
       [ 4, 49,  1,  1],
       [36, 81, 16, 16]])

In [ ]:
np.mean(arr1)

np.float64(3.8333333333333335)

In [ ]:
np.median(arr1)

np.float64(4.0)

In [ ]:
np.std(arr1)

np.float64(2.4776781245530843)

In [ ]:
np.var(arr1)

np.float64(6.138888888888888)

In [ ]:
np.min(arr1)

np.int64(1)

In [ ]:
np.max(arr1)

np.int64(9)