<a href="https://colab.research.google.com/github/MUHAMMAD-SULEMAN-10/NumPy/blob/main/Numpy_part_3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Sort , Search & Counting function

In [ ]:
import numpy as np



In [ ]:
arr= np.array([4,3,3,5,6,72,3,3455,5,4,5,6])

In [ ]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
np.sort(arr)

array([   3,    3,    3,    4,    4,    5,    5,    5,    6,    6,   72,
       3455])

In [ ]:
np.searchsorted(arr, 34) # it will tell us 34 will be at 12 index posirion in a sorted order

np.int64(12)

In [ ]:
arr1 = np.array([0,345, 345, 0,0,0,0,0,])

In [ ]:
# count_nonzeor fun will tell us how many non zero values are in the data

np.count_nonzero(arr1)

2

In [ ]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
np.where(arr > 6) # it will tell abou the index

(array([5, 7]),)

In [ ]:
np.extract(arr>6 , arr) # now it will give the data values form the arr parameter

array([  72, 3455])

In [ ]:
# Byte Swapping function

arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
arr.byteswap() # will convert the data into a bytes one by one

array([ 288230376151711744,  216172782113783808,  216172782113783808,
        360287970189639680,  432345564227567616, 5188146770730811392,
        216172782113783808, 9154973617514086400,  360287970189639680,
        288230376151711744,  360287970189639680,  432345564227567616])

## Copies & Views

In [ ]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
a = np.copy(arr) #deep copy will occer

In [ ]:
a

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
b = arr.view() # it same like shallow copy concept not new data position it will take same var data position

In [ ]:
b = arr

In [ ]:
b

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
arr

array([   4,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
b[0] = 65

In [ ]:
b

array([  65,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

In [ ]:
arr

array([  65,    3,    3,    5,    6,   72,    3, 3455,    5,    4,    5,
          6])

# Matrix Library

## matlib = Matrix Library

In [ ]:
import numpy.matlib as nm

In [ ]:
np.zeros(5) # it will create matrix

#not the array it will careate

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Linear Algebra

In [ ]:
arr1 = np.random.randint([[2,3], [4,5]])

In [ ]:
arr2 = np.random.randint([[5,3], [2,5]])

In [ ]:
np.dot(arr1, arr2)

array([[2, 2],
       [3, 3]])

In [ ]:
arr1@arr2

array([[2, 2],
       [3, 3]])