<a href="https://colab.research.google.com/github/MUHAMMAD-SULEMAN-10/NumPy-/blob/main/Numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
l = [1,2,3,4]


In [ ]:
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
#deimensions

#2D
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.asarray(l)

#asarray is a function

array([1, 2, 3, 4])

In [ ]:
a = [2,3,4]

In [ ]:
#asanarray we can also used funciton

np.asanyarray(a)


array([2, 3, 4])

In [ ]:
#use matrix

b = np.matrix(l)

#matrx by default is a 2D
#matrix is a subset of array

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
# now if we used np on the b asanyarray it will  remain the matrix


np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [ ]:
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
#create a new variable c and assign a


c = a



In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
#if we chnaged the in c update the values then change the list
#and c will poin the same variable in the memory location and if we change in the c then will also occure in the a.

#it is a shallow copy

c[0] = 100

In [ ]:
c

array([100,   2,   3,   4])

In [ ]:
#now the changed will also be in the a 100 added in the a list also

a

array([100,   2,   3,   4])

In [ ]:
d = np.copy(a)

In [ ]:
d

array([100,   2,   3,   4])

In [ ]:
a

array([100,   2,   3,   4])

In [ ]:
#now change in the a

a[1] = 400

In [ ]:
a

array([100, 400,   3,   4])

In [ ]:
# But if we check the d value then there will be no change in the d

d

#because we compeletely copy it in a new location. d has new data location not the a location.

# its a deep copy concept.


array([100,   2,   3,   4])

In [ ]:
# Generate different different diemensions of array

np.fromfunction(lambda i,j : i==j, (3,3))

#Here we are creating the 3*3 = 9 elements matrix and like 0,1,2 row and then 0,1,2 col

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j, (3,3))

# fromfunction is type of a function which will help us to in terms of arrays at any point of time.

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable ,float)

# fromiter function we can also make an array



array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
# fromstring function if we passed it will convert the dtring into an array

np.fromstring('234 234 555', sep=' ') # separate on the basis of the space

array([234., 234., 555.])

In [ ]:

np.fromstring('234,44', sep=',')

array([234.,  44.])

# Datatypes in Numpy

In [ ]:
# make a list

l = [1,2,3,4,5]


In [ ]:
arr = np.array(l)

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
# if we want to check the dimensions of the array

In [ ]:
arr.ndim

1

In [ ]:
arr2 = np.array([[1,2,3,4], [2,3,4,5]])

In [ ]:
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [ ]:
arr2.ndim

2

In [ ]:
# Now i want check the size of the arr2

arr2.size

#will give the elements of the arr2

8

In [ ]:
arr.shape

# shape will tell about the rows and cols

(5,)

In [ ]:
arr2.shape

(2, 4)

In [ ]:
#want to check the data type

arr.dtype

dtype('int64')

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
# make another an array

ar22 = np.array([(1.4,45,45), (23,45,66)])


In [ ]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [ ]:
ar22.dtype

#it will be float

dtype('float64')

In [ ]:
# range function
range (5)

range(0, 5)

In [ ]:
#call in a list

list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
# now can we generate the floating poin number in a range

#not possible

list(range(0.1 , 4))

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
#bu the default in the numpy arange will work and generate the numbers in a float

np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [ ]:

np.arange(2.3, 5.6, .3) # .3 here is a jump

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
list(np.arange(2.3, 5.6))


#numpy here tells us we can not only generate the interger values we can also generate the points vlaues.

[np.float64(2.3), np.float64(3.3), np.float64(4.3), np.float64(5.3)]

In [ ]:
# linspace function

#it will take a line 1 to 5 and will divide and produce in 10 data set
np.linspace(1,5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
# zeors function

# it will create the one D array take data 5

np.zeros(5) # 5 means here 1D will

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4)) # will be 3 rows and 5 cols in a 2D format

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2)) # this is a 3D and 3 here is kind of 3 cross mattrics and 4*2 = 8 elements

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((3,4,2,3)) # here 3 is indiecate we have 3 matircs and each is 4D and 4 indicates we have 4 and 2 * 3 = 6 elems each have

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
# ones funciton


np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
on = np.ones((3,4,4))

In [ ]:
on

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
on *4 #now it will add 4 to each matric

array([[[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]],

       [[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]]])

In [ ]:
# empty function

#now the empty array has been created

np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [ ]:
# entity matric create with the eye and dimensions is same and in the diognal have 1,1,1...
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# linspace funciton

np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [ ]:
# logspace funcition

#same it will also create a log data of in 10 datapoints from 2 to 5

np.logspace(2,5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [ ]:
#but we want to calculate on the base 2

np.logspace(2,5, 10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

# some important functions in the numpy

In [ ]:
# random function
# will produce random data

np.random.randn(3,4) # 3 cross 4 have 3 rows and 4 cols

array([[ 0.40777941, -0.60980715, -0.36020948, -0.42501679],
       [ 0.12775494,  0.12427061,  1.12963048,  0.18665452],
       [ 0.14005738, -0.08345   , -0.10921838, -0.59351063]])

In [ ]:
arr = np.random.randn(3,4)

#randn will geenrate the data where the mean is 0 and std = 1

In [ ]:
arr

array([[ 2.38167856,  0.63356449, -0.31685496, -0.80390624],
       [-1.83723775,  1.40557466, -0.84995947,  0.05694484],
       [ 0.27592349,  1.63296179, -1.15224326, -0.17632629]])

In [ ]:
# but now we want to store this random data in a data frame for it we need to import the pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(arr)

In [ ]:
df

0         1         2         3
0  2.381679  0.633564 -0.316855 -0.803906
1 -1.837238  1.405575 -0.849959  0.056945
2  0.275923  1.632962 -1.152243 -0.176326

In [ ]:
np.random.rand(3,4)

# here the rand will just randomly produce the data not beteen in 1 and 0

array([[0.21281929, 0.81821154, 0.35649619, 0.35044452],
       [0.89907228, 0.85062762, 0.88507311, 0.5565743 ],
       [0.42055542, 0.99447748, 0.03944667, 0.57434626]])

In [ ]:
# randint fucniton
# will generate the interger data set only


data=np.random.randint(1,110, (300,400))

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     18   13   12   99    1  101   14   61   73   38  ...  109  106   65   
1     73  102    2   73   22   83   66   55   79   45  ...   13   66   90   
2     90   94   39   26  104   61  107   90   20   89  ...    6   16    6   
3     39   80    8    3   47   19   10    2    7   36  ...   21   44   55   
4     22   79   77   92   30  100   27    9    1  109  ...   92   94   23   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   38    6   57   85   79   78   85   91   56   25  ...   34   35   47   
296   15    4   78   79   30   19   79   78   50   53  ...   13   29   79   
297   54   45    3   62   48   27   98   61  102   68  ...   89   12   13   
298  108   38   93   88   89   80   35  105   16   44  ...   73    4   72   
299   58   78   24   35   89    1   42    1  108  106  ...   65  101    3   

     393  394  395  396  397  398  399  
0     41   76    2   74   30   62   16  
1     67    7   26   46   91   32   12  
2     63   84  101   24    2   13   81  
3     44   77    4   92    4   78   90  
4     18   87   23   33   44   71  103  
..   ...  ...  ...  ...  ...  ...  ...  
295   54   33   48  102   96   95   55  
296   80   99   26   25   84   97   12  
297   23   89   25   88   25   89   77  
298    4   57   35   74   48   64    2  
299   14   39  102   39   63   59  108  

[300 rows x 400 columns]

In [ ]:
#now store this data in a csv file


(df).to_csv('test.csv')

In [ ]:
# reshape function

#it will widley used in ML during the data analysis

arr1 = np.random.rand(6,2)

In [ ]:
arr1

array([[0.89075237, 0.66046182],
       [0.37396136, 0.94237954],
       [0.39825603, 0.00825195],
       [0.97151487, 0.20131558],
       [0.96166512, 0.4504178 ],
       [0.46157807, 0.30942111]])

In [ ]:
arr1.reshape((6,-1)) # it will convert in a 6,2 automatically and assume the - 1 ==2

array([[0.89075237, 0.66046182],
       [0.37396136, 0.94237954],
       [0.39825603, 0.00825195],
       [0.97151487, 0.20131558],
       [0.96166512, 0.4504178 ],
       [0.46157807, 0.30942111]])

In [ ]:
arr.reshape(6,3)

NameError: name 'arr1' is not defined

In [ ]:
# get a specific value
arr1[1][1]


np.float64(0.9423795378014498)

In [ ]:
arr1[0:5]

array([[0.89075237, 0.66046182],
       [0.37396136, 0.94237954],
       [0.39825603, 0.00825195],
       [0.97151487, 0.20131558],
       [0.96166512, 0.4504178 ]])

In [ ]:
arr1[1:2]

array([[0.37396136, 0.94237954]])

In [ ]:
arr1[2:5,1] # start from 2 row and include 5th col and in this rows and cols get the values in a colom 1 with respect to dimension

array([0.00825195, 0.20131558, 0.4504178 ])

In [ ]:
#make a random data

arr = np.random.randint(1,100, (5,5))

In [ ]:
arr

array([[15, 89, 42, 76, 42],
       [ 4, 90, 46,  7, 20],
       [59, 76, 22, 13, 73],
       [52, 51, 86, 94, 15],
       [ 8, 22, 95, 29,  5]])

In [ ]:
#now get the data grater than 50

arr>50

array([[False,  True, False,  True, False],
       [False,  True, False, False, False],
       [ True,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True, False, False]])

In [ ]:
#now get the true data only


# make a array and then get its a subsetting.
arr[arr>50]

array([89, 76, 90, 59, 76, 73, 52, 51, 86, 94, 95])

In [ ]:
# arr is availabel


arr

array([[15, 89, 42, 76, 42],
       [ 4, 90, 46,  7, 20],
       [59, 76, 22, 13, 73],
       [52, 51, 86, 94, 15],
       [ 8, 22, 95, 29,  5]])

In [ ]:
#now i want a specific data from the array

# these values: 76,22  51,86

arr[2:4, [1,2]] # 2 and 4 are rows but till 3 work and 1, 2 are cols

array([[76, 22],
       [51, 86]])

In [ ]:
# want to get 15 value

arr[0][0]

np.int64(15)

In [ ]:
# add a new value at 1st
# data manuplation


arr[0][0] = 5000

In [ ]:
arr

array([[5000,   89,   42,   76,   42],
       [   4,   90,   46,    7,   20],
       [  59,   76,   22,   13,   73],
       [  52,   51,   86,   94,   15],
       [   8,   22,   95,   29,    5]])

In [ ]:
# inbuilt funcitons genrate the random data in arrays

arr1 = np.random.randint(1,3 , (3,3))

arr2 = np.random.randint(1,3 , (3,3))

In [ ]:
arr1

array([[2, 1, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [ ]:
arr2

array([[2, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [ ]:
# nwo add these two arrays data
# it will adds the numbers on the basis of the indexes mapping will occure

arr1+arr2

array([[4, 3, 2],
       [4, 2, 4],
       [3, 2, 4]])

In [ ]:
arr1-arr2

array([[ 0, -1,  0],
       [ 0,  0,  0],
       [-1,  0,  0]])

In [ ]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [1. , 1. , 1. ],
       [0.5, 1. , 1. ]])

In [ ]:
arr1*arr2
# it will be index wisse multiplication not the matriics multiplication

array([[4, 2, 1],
       [4, 1, 4],
       [2, 1, 4]])

In [ ]:
# now how we can do matrices multiplication

# in which the 1st rows mul with the first col1,col2,col3 and so on.......

# and also the col values in the first matrix equal with the 2nd matrix col

In [ ]:
# use @ fro the matrix multiplication in numpy


arr1@arr2

array([[ 8,  6,  6],
       [10,  7,  8],
       [ 8,  5,  7]])

In [ ]:
arr1/0

#it will give us infinity

/tmp/ipython-input-1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
arr1 +100

array([[102, 101, 101],
       [102, 101, 102],
       [101, 101, 102]])

In [ ]:
arr1**2 # add the power one by one

array([[4, 1, 1],
       [4, 1, 4],
       [1, 1, 4]])

In [ ]:
# Broadcasting in Numpy

arr4 = np.zeros((4,4))

In [ ]:
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
row = np.array([1,2,3,4])

In [ ]:
row

array([1, 2, 3, 4])

In [ ]:
arr4 + row

# it will add row wise values and we are changing the values in a row
# this a row wise broadcasting adding one by one.

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
row.ndim

1

In [ ]:
row.shape

(4,)

In [ ]:
row.T #take a transpose but it will not traspose due to 1 row



array([1, 2, 3, 4])

In [ ]:
col = np.array([[1,2,3,4]])

In [ ]:
col.T # its changed due to 2D

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
col # it will same

array([[1, 2, 3, 4]])

In [ ]:
col.T + arr4


# here we are doing the col broadcasting one by one

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [ ]:
#More maths opearation


array2 = np.random.randint(1,4 , (3,4))

In [ ]:
array2

array([[2, 1, 1, 3],
       [2, 3, 1, 1],
       [2, 2, 2, 1]])

In [ ]:
# take a sqr root

np.sqrt(array2)

array([[1.41421356, 1.        , 1.        , 1.73205081],
       [1.41421356, 1.73205081, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356, 1.        ]])

In [ ]:
# take a exponantional

np.exp(array2)

array([[ 7.3890561 ,  2.71828183,  2.71828183, 20.08553692],
       [ 7.3890561 , 20.08553692,  2.71828183,  2.71828183],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 ,  2.71828183]])

In [ ]:
# take a Log10


np.log10(array2)

array([[0.30103   , 0.        , 0.        , 0.47712125],
       [0.30103   , 0.47712125, 0.        , 0.        ],
       [0.30103   , 0.30103   , 0.30103   , 0.        ]])